Feat/new commands
bokvilla/cholobot pull request #12
Opened 2017-07-06 22:07 UTC by vcabrales

### What does this PR do?
Adding new commands (jaja and chupala)

### How do I test it?
npm install
npm run start:dev and can send the commands mentioned in the PR

### Background context
When someone say something very funny you can express how funny it was
If someone needs to express a compliment to a friend

2017-07-06 22:13 UTC, ghost requested changes

2017-07-06 22:13 UTC, bokvilla commented on app/commands.js
> +    const index = Math.floor((Math.random() * staticResponses.chupala.length-1) + 1);
Random number could be generated from `getRandomNum` function if it receives a limit

2017-07-06 22:15 UTC, jtinoco22 commented on dist/commands.js
> +    var index = Math.floor(Math.random() * _staticResponses2.default.chupala.length - 1 + 1);
- 1 + 1 != 0 ?? WTF

2017-07-06 22:34 UTC, jtinoco22 commented on dist/commands.js
> +    var index = Math.floor(Math.random() * _staticResponses2.default.chupala.length - 1 + 1);
are you missing a parenthesis? any way you will change this to getRandomNum

2017-07-07 03:23 UTC, ghost requested changes

2017-07-07 03:23 UTC, jtinoco22 commented on app/commands.js
> +    const index = getRandomNum(staticResponses.chupala.length-1 + 1);
-1 + 1 == 0,  I think you can remove this.

2017-07-07 03:23 UTC, jtinoco22 commented on app/commands.js
> +    const index = getRandomNum(staticResponses.buenas.length-1 + 1);
Same here (length - 1 + 1) == length

2017-07-07 03:23 UTC, jtinoco22 commented on app/commands.js
> +const limit = 25;
You can change this to @bokvilla suggestion GIPHY_API_LIMIT

2017-07-07 14:58 UTC, ghost approved these changes

2017-07-07 17:10 UTC, ghost approved these changes

2017-07-07 17:10 UTC, merged